/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.au.cc.gallery;

import static  spark.Spark.*;
import java.util.Map;
import java.util.HashMap;
import spark.ModelAndView;
import spark.template.handlebars.HandlebarsTemplateEngine;

public class App {

    public String getGreeting() {
        return "Hello world.";
    }

    private static String listUsers() {
      	try {     
	    StringBuffer sb = new StringBuffer();
            UserDAO dao = Postgres.getUserDAO();
            for(User u: dao.getUsers()) 
	        sb.append(u.toString());
	    return sb.toString();
	} catch (Exception e) {
		return "Error: " + e.getMessage();	
	}
    }


    public static void main(String[] args) throws Exception {
	String portString = System.getenv("JETTY_PORT");
	if (portString == null || portString.equals(""))
	    port(5000);
	else
	    port(Integer.parseInt(portString));    
        get("/hello", (req, res) -> "Hello World");
	
    	new DatabaseMethods().addRoutes();
    
    	get("/users", (req, res) -> listUsers());
    
    }
}

